--- 
abstract: Checks if a Ticket has been updated in the given business hours
author: 
  - Kevin Falcone <falcone@bestpractical.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-Condition-UntouchedInBusinessHours
no_index: 
  directory: 
    - etc
    - html
    - po
    - var
    - inc
    - t
requires: 
  Business::Hours: 0
version: 0.01
