---
abstract: 'Checks if a Ticket has been updated in the given business hours'
author:
  - 'Kevin Falcone  C<< <falcone@bestpractical.com> >>'
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Condition-UntouchedInBusinessHours
no_index:
  directory:
    - inc
    - xt
requires:
  Business::Hours: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.02
